### ISSUE TITLE
Windows: Unable to start program

### ISSUE THREAD

**Issue by NathanaelThompson** [v3n/altertum#15]
**The error in question.**

![capture](https://cloud.githubusercontent.com/assets/6734422/10057562/ec521770-620e-11e5-999e-9d6051447b9e.JPG)

**Comment by v3n** [comment]
Not a bug. Set the correct project as the startup library and the project runs.

...running a library doesn't do anything.

**Comment by NathanaelThompson** [comment]
That makes sense. I suppose it's my fault for thinking vs would handle that
automagically.

**Comment by v3n** [comment]
Ayup. VS is wonky with startup projects + targets with GENie. I�ll look into options to getting it to set a default startup value.
