### ISSUE TITLE
Investigate and decide upon texture format(s)

### ISSUE THREAD

**Issue by v3n** [v3n/altertum#27]

**Comment by NathanaelThompson** [comment]
The industry standard for texture file type seems to be DDS with BC3 compression (Unity, Unreal, and Gamebryo all follow this convention). This obviously presents a problem for us if we want to maintain the cross-platform nature of the project as DDS is a M$/DirectX technology.  Although, there are always seem to be open source workarounds for platform-dependent tech. 

 Other than DDS, PNG and TGA seem to be the goto. 

Additionally, DDS files can be utilized in OpenGL via the GLSL ARB texture compression extension, however it is not part of the OpenGL standard and is not in all implementations of OpenGL.

**Comment by NathanaelThompson** [comment]
DDS seems to be the way we're heading.
